eka_str = input(f"sano joku luku")
toka_str = input(f"sano toinen luku")
kolmas_str = input(f"sano kolmas luku")
eka = float(eka_str)
toka = float(toka_str)
kolmas = float(kolmas_str)
summa = (eka+toka+kolmas)
tulo = (eka*toka*kolmas)
keskiarvo = (eka+toka+kolmas/3)
print (f"lukujen summa on {summa} , keskiarvo on {keskiarvo} ja tulo on {tulo}")